apiVersion: v2
name: onecx-chat-svc
version: 0.0.0
appVersion: 0.0.0
description: OneCX chat service
keywords:
  - chat
sources:
  - https://github.com/onecx/onecx-chat-svc
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-quarkus-app
    alias: app
    version: 0.42.0
    repository: oci://ghcr.io/onecx/charts